version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      args:
        - ENV=prod
    ports:
      - 80:80
  backend:
    build:
      context: ./backend
    ports:
      - 8080:3000
